"""Generate a complete `dev.tfvars` for every terraform module.

Two files, two jobs:

    example.tfvars   committed. Required variables set, optional ones shown
                     commented with their default. It is the reference a fresh
                     clone reads.
    dev.tfvars       gitignored, yours. EVERY variable set and uncommented, so
                     you can change any one of them by editing a value rather
                     than remembering to uncomment a line first.

Values come from, in order: what your dev.tfvars already says, then what
example.tfvars says, then the variable's declared default. **Anything you have
already set is kept** — this fills gaps, it does not overwrite your work.

Generated from the `variable` blocks themselves, so it cannot drift the way a
hand-maintained file does. That is not hypothetical: every one of these was
hand-written once and five of them were missing variables.

    uv run scripts/gen_tfvars.py            # fill gaps, keep what you set
    uv run scripts/gen_tfvars.py --show     # print what would change, write nothing
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TF = ROOT / "terraform"

VARIABLE = re.compile(r'^variable\s+"([a-z0-9_]+)"\s*\{(.*?)^\}', re.M | re.S)
DEFAULT = re.compile(r'^\s*default\s*=\s*(.+?)\s*$', re.M)
DESCRIPTION = re.compile(r'^\s*description\s*=\s*"(.*?)"\s*$', re.M | re.S)


def modules() -> list[Path]:
    return sorted(d for d in TF.iterdir() if d.is_dir() and d.name[0].isdigit())


def declared(text: str) -> list[tuple[str, str | None, str | None]]:
    """(name, default_literal_or_None, description_or_None) for each variable."""
    out = []
    for name, body in VARIABLE.findall(text):
        d = DEFAULT.search(body)
        desc = DESCRIPTION.search(body)
        out.append((name, d.group(1) if d else None, desc.group(1) if desc else None))
    return out


def value_in(path: Path, name: str) -> str | None:
    """The value assigned to `name`, whether or not the line is commented out."""
    if not path.exists():
        return None
    found = re.search(rf"^\s*#?\s*{name}\s*=\s*(.+?)\s*(?:#.*)?$", path.read_text(), re.M)
    return found.group(1) if found else None


def render(module: Path) -> str:
    dev = module / "dev.tfvars"
    example = module / "example.tfvars"
    lines = [
        f"# {module.name} — every variable this module declares, set explicitly.",
        "#",
        "# Generated by `uv run scripts/gen_tfvars.py`, which keeps whatever you have",
        "# already set. Gitignored: this is your working copy, not the committed",
        "# reference (that is example.tfvars).",
        "",
    ]

    for name, default, desc in declared((module / "main.tf").read_text()):
        value = value_in(dev, name) or value_in(example, name) or default
        if value is None:
            value = '"CHANGE-ME"'
        if desc:
            short = " ".join(desc.split())
            if len(short) > 74:
                short = short[:71] + "..."
            lines.append(f"# {short}")
        if default is None:
            lines.append("# required — no default")
        lines.append(f"{name} = {value}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--show", action="store_true", help="print, do not write")
    args = parser.parse_args()

    for module in modules():
        body = render(module)
        target = module / "dev.tfvars"
        count = len(declared((module / "main.tf").read_text()))

        if args.show:
            print(f"===== {target.relative_to(ROOT)} =====")
            print(body)
            continue

        kept = sum(1 for n, _, _ in declared((module / "main.tf").read_text())
                   if value_in(target, n) is not None)
        target.write_text(body)
        print(f"  {target.relative_to(ROOT)}  —  {count} variables ({kept} kept from yours)")

    if not args.show:
        print("\n  These are gitignored. example.tfvars stays the committed reference.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
